### ISSUE TITLE
Erebus: Block o' Bones Compass item added on every respawn

### ISSUE THREAD

**Issue by satoshinm** [satoshinm/modpack#96]
Can the free "Block o' Bones Compass" from Erebus be disabled? It gets added to the player inventory every time after they did and respawn:

<img width="352" alt="screen shot 2017-07-16 at 11 44 24 pm" src="https://user-images.githubusercontent.com/26856618/28257563-c0614d8a-6a80-11e7-8316-730d24fd9cbd.png">

http://the-erebus.wikia.com/wiki/Block_o%27_Bones

> Made as an elegant and flavourful solution to losing items on death, Block o' Bones holds on to your entire inventory at the time of death, and remains in the exact spot of your death until broken.

Gravestones from OpenBlocks already do this.

Was crafting most of the Block o' Bones into bonemeal, but to avoid clutter, consider disabling.

**Comment by choekstr** [comment]
in config file: 
B:"Block O' Bones Inventory Save"=false

**Comment by satoshinm** [comment]
@choekstr Thank you for the tip!
